import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import ThemeProviders from "./ThemeProviders";
import MovieCategories from "@/components/categories/Categories";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import SearchBox from "@/components/search/SearchBox";
import { Suspense } from "react";
import AppLoader from "@/components/loader/AppLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProviders>
          <Header />
          <MovieCategories />
          <SearchBox />
          <Suspense fallback={<div>This is loader</div>}>{children}</Suspense>
        </ThemeProviders>
      </body>
    </html>
  );
}
